const assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const source=fs.readFileSync('app.js','utf8').replace("window.WorkApp={navigate};document.addEventListener('DOMContentLoaded',init);",'window.WorkApp={state,ui,renderAdminBudget};');
const dom=new JSDOM('<div id="page-content"></div><div id="modal-root"></div><div id="toast"></div>',{url:'http://localhost/',runScripts:'outside-only'});
const errors=[];dom.window.addEventListener('error',e=>{errors.push(e.error);e.preventDefault();});
dom.window.WorkMonthly=require('../monthly-hours');dom.window.eval(source);const app=dom.window.WorkApp,doc=dom.window.document;
const d={selectedTermId:'T',activeTermId:'T',features:{monthlySettlement:true,monthlyFinalAmount:true},settings:{SEMESTER_START:'2026-09-01',SEMESTER_END:'2026-12-31',BREAK_END:'2026-12-31',WAGE_2026:'10320'},students:[{STUDENT_KEY:'A',NAME:'학생A',ACTIVE:'Y'},{STUDENT_KEY:'B',NAME:'학생B',ACTIVE:'Y'},{STUDENT_KEY:'C',NAME:'학생C',ACTIVE:'N'}],schedules:[{SCHEDULE_ID:'S',STUDENT_KEY:'A',ACTIVE:'Y',PERIOD_TYPE:'학기중',DAY:'목',START:'9:00',END:'12:00'},{SCHEDULE_ID:'BAD',STUDENT_KEY:'B',ACTIVE:'Y',PERIOD_TYPE:'학기중',DAY:'목',START:'bad',END:'12:00'}],budgets:[],monthlyCorrections:[]};
app.state.adminData=d;app.ui.budgetMonth='2026-10';app.renderAdminBudget();assert.equal(doc.querySelectorAll('.monthly-correct').length,3);
function click(key){doc.querySelector(`.monthly-correct[data-key="${key}"]`).click();assert.equal(errors.length,0,errors.map(e=>e.stack).join('\n'));const form=doc.querySelector('#monthly-correction-form');assert.ok(form,'button click must create modal');assert.ok(doc.querySelector('.modal-head').textContent.includes(app.ui.budgetMonth));return form;}
let form=click('A');assert.equal(form.elements.hours.value,'15');assert.equal(form.elements.amountMode.value,'AUTO');assert.match(form.textContent,/시간 × 시급 자동계산/);doc.querySelector('.modal-cancel').click();assert.equal(doc.querySelector('#modal-root').innerHTML,'');form=click('A');
form.elements.amountMode.value='DIRECT';form.elements.amountMode.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal(form.elements.amount.disabled,false);form.elements.amount.value='0';form.elements.amount.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.match(doc.querySelector('#monthly-amount-preview').textContent,/최종 금액: 0원/);doc.querySelector('.modal-close').click();assert.equal(doc.querySelector('#modal-root').innerHTML,'');
form=click('B');assert.match(form.textContent,/근무표 기준 확인 필요/);assert.equal(form.elements.hours.disabled,false);doc.querySelector('.modal-cancel').click();click('C');doc.querySelector('.modal-backdrop').click();assert.equal(doc.querySelector('#modal-root').innerHTML,'');
d.monthlyCorrections=[{TERM_ID:'T',STUDENT_KEY:'A',MONTH:'2026-10',MODE:'OVERRIDE',BASE_MINUTES:900,AFTER_MINUTES:600,VERSION:1,AMOUNT_MODE:'DIRECT',AFTER_AMOUNT:0}];app.renderAdminBudget();form=click('A');assert.equal(form.elements.amountMode.value,'KEEP');assert.match(form.textContent,/기존 직접입력 금액 유지/);doc.querySelector('.modal-cancel').click();
d.features.monthlyFinalAmount=false;app.renderAdminBudget();form=click('A');assert.equal(form.elements.amountMode,undefined);doc.querySelector('.modal-cancel').click();
app.ui.budgetMonth='2026-11';app.renderAdminBudget();click('A');assert.match(doc.querySelector('.modal-head').textContent,/2026-11/);doc.querySelector('.modal-cancel').click();
d.readOnly=true;app.renderAdminBudget();assert.equal(doc.querySelectorAll('.monthly-correct').length,0);assert.equal(errors.length,0);dom.window.close();
console.log('monthly-modal: click/open/cancel/reopen, close/backdrop, normal/unknown/zero students, amount preview/keep, month and feature guards passed; no API writes');
