const assert=require('node:assert/strict');
const {runtime,rows}=require('./term-model.test');
const {context:c,book}=runtime();c.setupSystem();
assert.equal(c.getAdminDashboard_({pin:'1234'}).features.monthlySettlement,false);
c.setupMonthlyHours();c.setupMonthlyHours();
const d=c.getAdminDashboard_({pin:'1234'});assert.equal(d.features.monthlySettlement,true);
const summary=c.WorkMonthly.summarize(d,'2026-09');assert.equal(summary[0].baseMinutes,540);assert.equal(summary[0].baseAmount,null);
const baseSheets=JSON.stringify(['학생DB','고정근무표','출근불가','예산'].map(n=>rows(book,n)));
const p={pin:'1234',termId:'2026-2',studentKey:'K01',month:'2026-09',mode:'OVERRIDE',minutes:480,reason:'실제 근무시간 반영',actorLabel:'검토자A',expectedBaseMinutes:540,expectedVersion:0,requestId:'REQUEST_0001'};
const e=c.saveMonthlyCorrection_(p).event;assert.equal(e.BEFORE_MINUTES,540);assert.equal(e.AFTER_MINUTES,480);assert.equal(e.BASE_MINUTES,540);assert.equal(e.ACTOR_ROLE,'ADMIN');assert.match(e.MODIFIED_AT,/Z$/);
assert.equal(c.saveMonthlyCorrection_(p).replayed,true);assert.equal(rows(book,'월별시간보정').length,1);
assert.throws(()=>c.saveMonthlyCorrection_({...p,reason:'다른 내용'}),/식별자/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,pin:'wrong'}),/PIN/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,requestId:'REQUEST_STALE'}),/변경/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,studentKey:'OTHER',requestId:'REQUEST_OTHER'}),/학생/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,expectedVersion:1,requestId:'REQUEST_BAD',minutes:-1}),/정수/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,expectedVersion:1,requestId:'REQUEST_BAD',minutes:'1.5'}),/정수/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,expectedVersion:1,requestId:'REQUEST_BAD',reason:' '}),/사유/);
assert.throws(()=>c.saveMonthlyCorrection_({...p,month:'2026-08',expectedVersion:0,requestId:'REQUEST_BAD'}),/학기 밖/);
let corrected=c.WorkMonthly.summarize(c.getAdminDashboard_({pin:'1234'}),'2026-09')[0];assert.equal(corrected.appliedMinutes,480);
c.upsertTermSetting_('2026-2','WAGE_2026','10320');corrected=c.WorkMonthly.summarize(c.getAdminDashboard_({pin:'1234'}),'2026-09')[0];assert.equal(corrected.baseAmount,92880);assert.equal(corrected.settlementAmount,82560);assert.equal(corrected.paymentConfirmed,false);
c.saveMonthlyCorrection_({...p,minutes:0,expectedVersion:1,requestId:'REQUEST_ZERO'});assert.equal(c.WorkMonthly.summarize(c.getAdminDashboard_({pin:'1234'}),'2026-09')[0].settlementAmount,0);
c.saveMonthlyCorrection_({...p,mode:'BASE',expectedVersion:2,requestId:'REQUEST_RESET',reason:'원본 기준 복원'});assert.equal(c.WorkMonthly.summarize(c.getAdminDashboard_({pin:'1234'}),'2026-09')[0].appliedMinutes,540);assert.equal(rows(book,'월별시간보정').length,3);
assert.equal(JSON.stringify(['학생DB','고정근무표','출근불가','예산'].map(n=>rows(book,n))),baseSheets);
// A new term must not inherit prior term corrections, and prior term remains read-only.
c.createTerm_({pin:'1234',year:'2027',termType:'1',termName:'2027-1학기',startDate:'2027-03-01',endDate:'2027-08-31',copyStudents:'Y',copySchedules:'Y'});
c.activateTerm_({pin:'1234',activateTermId:'2027-1'});
assert.throws(()=>c.saveMonthlyCorrection_({...p,expectedVersion:3,requestId:'REQUEST_PAST'}),/읽기 전용/);
assert.equal(c.getAdminDashboard_({pin:'1234',termId:'2027-1'}).monthlyCorrections.length,0);
assert.equal(c.getAdminDashboard_({pin:'1234',termId:'2026-2'}).monthlyCorrections.length,3);
const student=c.getStudentDashboard_({studentId:'20260001',loginPin:'1111'});assert.equal(student.monthlyCorrections,undefined);assert.equal(student.features.monthlySettlement,undefined);
console.log('monthly-settlement-backend: schema setup, auth, server baseline, audit, replay, conflict, zero/reset, amounts, term isolation, student exclusion and original preservation passed');
